spring:
  datasource:
    name: smd
    url: jdbc:tc:postgresql:18-alpine:///smd?TC_INITSCRIPT=db/smd/event-store-schema.sql
    username: test_user
    password: test_password

smd:
  event-store:
    enabled: true
    scheduling:
      initial-delay: 0ms
      polling-delay: 100ms
logging:
  level:
    app.dodb: DEBUG
