spring:
  application:
    name: ticket-service
  datasource:
    url: jdbc:postgresql://localhost:5432/tickets
    username: tickets
    password: tickets
  flyway:
    enabled: true

smd:
  event-store:
    enabled: true
    scheduling:
      initial-delay: 100ms
      polling-delay: 100ms
      thread-pool-size: 2
    processing:
      batch-size: 100
      max-retries: 3
      retry-backoff:
        strategy: fixed
        fixed-delay: 100ms

logging:
  level:
    app.dodb.smd.ticket: INFO
